name: keyakinan
description: Sample Vania backend web application framework
version: 1.0.0

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  vania: ^0.6.2
  sqflite: ^2.0.0
  path: ^1.8.0
  webview_flutter: any


dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  pointycastle: 3.7.3
  meta: ^1.16.0